import PDFDocument from 'pdfkit';
import { query } from './db.js';

/**
 * Generate a PDF performance report for a client and pipe it to the response.
 * @param {string} clientId
 * @param {string} from  ISO date string
 * @param {string} to    ISO date string
 * @param {import('express').Response} res
 */
export async function generateClientReport(clientId, from, to, res) {
    // Fetch client info
    const clientResult = await query('SELECT name, industry, monthly_budget FROM clients WHERE id = $1 AND is_active = true', [clientId]);
    if (clientResult.rows.length === 0) {
        throw new Error('Client not found');
    }
    const client = clientResult.rows[0];

    // Fetch aggregated metrics
    const metricsResult = await query(
        `SELECT
       COALESCE(SUM(spend), 0)       AS total_spend,
       COALESCE(SUM(leads), 0)       AS total_leads,
       COALESCE(SUM(reach), 0)       AS total_reach,
       COALESCE(SUM(impressions), 0) AS total_impressions,
       COALESCE(SUM(clicks), 0)      AS total_clicks,
       COALESCE(SUM(conversions), 0) AS total_conversions,
       COALESCE(SUM(revenue), 0)     AS total_revenue
     FROM campaign_metrics
     WHERE client_id = $1 AND date >= $2 AND date <= $3`,
        [clientId, from, to]
    );
    const m = metricsResult.rows[0];

    // Fetch per-campaign breakdown
    const campaignResult = await query(
        `SELECT c.name AS campaign_name, c.platform, c.status,
            COALESCE(SUM(cm.spend), 0) AS spend,
            COALESCE(SUM(cm.leads), 0) AS leads,
            COALESCE(SUM(cm.clicks), 0) AS clicks
     FROM campaigns c
     LEFT JOIN campaign_metrics cm ON cm.campaign_id = c.id AND cm.date >= $2 AND cm.date <= $3
     WHERE c.client_id = $1
     GROUP BY c.id, c.name, c.platform, c.status
     ORDER BY spend DESC`,
        [clientId, from, to]
    );

    // Build PDF
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${client.name.replace(/[^a-zA-Z0-9]/g, '_')}_report.pdf"`);
    doc.pipe(res);

    // Header
    doc.fontSize(22).fillColor('#1E293B').text('CloudCRM', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor('#6366F1').text('Performance Report', { align: 'center' });
    doc.moveDown(0.5);

    // Client info
    doc.fontSize(11).fillColor('#64748B')
        .text(`Client: ${client.name}`)
        .text(`Industry: ${client.industry || 'N/A'}`)
        .text(`Period: ${from} to ${to}`)
        .text(`Monthly Budget: $${Number(client.monthly_budget || 0).toLocaleString()}`);
    doc.moveDown(1);

    // Summary metrics
    doc.fontSize(14).fillColor('#1E293B').text('Summary');
    doc.moveDown(0.3);

    const cpl = Number(m.total_leads) > 0 ? (Number(m.total_spend) / Number(m.total_leads)).toFixed(2) : 'N/A';
    const roas = Number(m.total_spend) > 0 ? (Number(m.total_revenue) / Number(m.total_spend)).toFixed(2) : 'N/A';

    doc.fontSize(10).fillColor('#334155');
    const summaryData = [
        ['Total Spend', `$${Number(m.total_spend).toLocaleString()}`],
        ['Total Leads', Number(m.total_leads).toLocaleString()],
        ['Total Reach', Number(m.total_reach).toLocaleString()],
        ['Total Impressions', Number(m.total_impressions).toLocaleString()],
        ['Total Clicks', Number(m.total_clicks).toLocaleString()],
        ['Cost Per Lead', `$${cpl}`],
        ['ROAS', `${roas}x`],
    ];
    summaryData.forEach(([label, value]) => {
        doc.text(`${label}: ${value}`);
    });
    doc.moveDown(1);

    // Campaign breakdown
    if (campaignResult.rows.length > 0) {
        doc.fontSize(14).fillColor('#1E293B').text('Campaign Breakdown');
        doc.moveDown(0.3);

        doc.fontSize(9).fillColor('#64748B');
        campaignResult.rows.forEach((c) => {
            doc.fillColor('#1E293B').text(c.campaign_name, { continued: false });
            doc.fillColor('#64748B')
                .text(`  Platform: ${c.platform} | Status: ${c.status} | Spend: $${Number(c.spend).toLocaleString()} | Leads: ${c.leads} | Clicks: ${c.clicks}`);
            doc.moveDown(0.3);
        });
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#94A3B8')
        .text(`Generated by CloudCRM on ${new Date().toISOString().split('T')[0]}`, { align: 'center' });

    doc.end();
}
