import crypto from 'crypto';
import { query } from '../services/db.js';
import { createUserSchema, updateUserSchema } from '../validators/users.js';
import { uuidParamSchema } from '../validators/clients.js';
import { sendKeycloakCredentialsEmail } from '../services/email.js';
import {
    deleteKeycloakUser,
    disableKeycloakUser,
    isKeycloakAdminConfigured,
    provisionKeycloakUser,
    syncKeycloakUser,
} from '../services/keycloak.js';

function toAppRole(dbRole) {
    return dbRole === 'agency_admin' ? 'admin' : dbRole;
}

// ─── GET /api/users ─────────────────────────────────────────
export async function listUsers(req, res) {
    const roleFilter = req.query.role; // Optional: ?role=employee or ?role=manager
    let sql = `SELECT u.id, u.email, u.name, u.role, u.client_id, u.is_active,
            u.created_at, u.last_login, c.name AS client_name
     FROM users u
     LEFT JOIN clients c ON c.id = u.client_id`;
    const values = [];

    if (roleFilter) {
        sql += ` WHERE u.role = $1`;
        values.push(roleFilter);
    }

    sql += ` ORDER BY u.created_at DESC`;

    const result = await query(sql, values);

    // For employee users, also load their assignment count
    const users = result.rows.map((u) => ({
        ...u,
        display_role: toAppRole(u.role),
    }));

    return res.json({ users });
}

// ─── GET /api/users/me ──────────────────────────────────────
export async function getMe(req, res) {
    const result = await query(
        `SELECT u.id, u.email, u.name, u.role, u.client_id, u.is_active,
            u.created_at, u.last_login, c.name AS client_name
     FROM users u
     LEFT JOIN clients c ON c.id = u.client_id
     WHERE u.id = $1`,
        [req.user.user_id]
    );

    if (result.rows.length === 0) return res.status(404).json({ error: 'User not found' });

    const user = {
        ...result.rows[0],
        display_role: toAppRole(result.rows[0].role),
    };

    // For employees, also return assigned clients
    if (user.role === 'employee') {
        const assignments = await query(
            `SELECT eca.id AS assignment_id, c.id AS client_id, c.name AS client_name, eca.assigned_at
             FROM employee_client_assignments eca
             JOIN clients c ON c.id = eca.client_id AND c.is_active = true
             WHERE eca.employee_id = $1
             ORDER BY eca.assigned_at DESC`,
            [req.user.user_id]
        );
        user.assigned_clients = assignments.rows;
    }

    return res.json({ user });
}

// ─── POST /api/users ────────────────────────────────────────
export async function createUser(req, res) {
    if (!isKeycloakAdminConfigured()) {
        return res.status(503).json({
            error: 'Keycloak admin provisioning is not configured',
        });
    }

    const parsed = createUserSchema.safeParse(req.body);
    if (!parsed.success) {
        return res.status(400).json({ error: 'Invalid input', details: parsed.error.flatten().fieldErrors });
    }

    const { email, name, role } = parsed.data;

    // Check existing
    const existing = await query(`SELECT id FROM users WHERE email = $1`, [email]);
    if (existing.rows.length > 0) {
        return res.status(409).json({ error: 'A user with this email already exists' });
    }

    // Generate temp password if none provided
    let password = parsed.data.password;
    let isAutoGenerated = false;
    if (!password) {
        password = crypto.randomBytes(8).toString('base64url').slice(0, 12) + '!A1';
        isAutoGenerated = true;
    }

    const displayRole = toAppRole(role);

    let provisioned;
    try {
        provisioned = await provisionKeycloakUser({
            email,
            name,
            role: displayRole,
            tempPassword: password,
        });
    } catch (err) {
        const message = err instanceof Error ? err.message : 'Failed to provision Keycloak user';
        const status = message.includes('already exists') ? 409 : 502;
        return res.status(status).json({ error: message });
    }

    let result;
    try {
        result = await query(
            `INSERT INTO users (email, role, name, keycloak_user_id)
         VALUES ($1, $2, $3, $4)
         RETURNING id, email, name, role`,
            [email, role, name, provisioned.id]
        );
    } catch (err) {
        await deleteKeycloakUser(provisioned.id);
        throw err;
    }

    try {
        await sendKeycloakCredentialsEmail({ email, password, name, role: displayRole });
    } catch (err) {
        console.error(`[EMAIL] Failed to send Keycloak credentials to ${email}:`, err);
    }

    const response = {
        user: { ...result.rows[0], display_role: displayRole },
        message: `${displayRole.charAt(0).toUpperCase() + displayRole.slice(1)} created in Keycloak. Credentials have been sent to ${email}.`,
    };

    // Show temp password to admin (one-time display)
    if (isAutoGenerated) {
        response.temp_password = password;
        response.message += ' Temporary password shown above — it will not be displayed again.';
    }

    return res.status(201).json(response);
}

// ─── PATCH /api/users/:id ───────────────────────────────────
export async function updateUser(req, res) {
    const idParsed = uuidParamSchema.safeParse(req.params.id);
    if (!idParsed.success) return res.status(400).json({ error: 'Invalid user ID' });

    const parsed = updateUserSchema.safeParse(req.body);
    if (!parsed.success) {
        return res.status(400).json({ error: 'Invalid input', details: parsed.error.flatten().fieldErrors });
    }

    const fields = [];
    const values = [];
    let i = 1;

    for (const [key, value] of Object.entries(parsed.data)) {
        fields.push(`${key} = $${i}`);
        values.push(value);
        i++;
    }

    if (fields.length === 0) return res.status(400).json({ error: 'No fields to update' });

    const existingResult = await query(
        `SELECT id, email, name, role, is_active, keycloak_user_id
         FROM users
         WHERE id = $1`,
        [idParsed.data]
    );
    if (existingResult.rows.length === 0) return res.status(404).json({ error: 'User not found' });

    const existingUser = existingResult.rows[0];
    const needsKeycloakSync =
        existingUser.keycloak_user_id &&
        (Object.prototype.hasOwnProperty.call(parsed.data, 'email') ||
            Object.prototype.hasOwnProperty.call(parsed.data, 'name') ||
            Object.prototype.hasOwnProperty.call(parsed.data, 'role') ||
            Object.prototype.hasOwnProperty.call(parsed.data, 'is_active'));

    if (needsKeycloakSync && !isKeycloakAdminConfigured()) {
        return res.status(503).json({
            error: 'Keycloak admin provisioning is not configured for user sync',
        });
    }

    values.push(idParsed.data);
    const result = await query(
        `UPDATE users SET ${fields.join(', ')} WHERE id = $${i} RETURNING id, email, name, role, is_active`,
        values
    );

    if (needsKeycloakSync) {
        await syncKeycloakUser({
            keycloakUserId: existingUser.keycloak_user_id,
            email: parsed.data.email,
            name: parsed.data.name,
            role: parsed.data.role ? toAppRole(parsed.data.role) : undefined,
            isActive:
                typeof parsed.data.is_active === 'boolean'
                    ? parsed.data.is_active
                    : undefined,
        });
    }

    return res.json({ user: result.rows[0] });
}

// ─── DELETE /api/users/:id ──────────────────────────────────
export async function deleteUser(req, res) {
    const idParsed = uuidParamSchema.safeParse(req.params.id);
    if (!idParsed.success) return res.status(400).json({ error: 'Invalid user ID' });

    // Prevent deleting yourself
    if (idParsed.data === req.user.user_id) {
        return res.status(400).json({ error: 'Cannot deactivate your own account' });
    }

    const existingResult = await query(
        `SELECT id, keycloak_user_id FROM users WHERE id = $1`,
        [idParsed.data]
    );
    if (existingResult.rows.length === 0) return res.status(404).json({ error: 'User not found' });

    const existingUser = existingResult.rows[0];
    if (existingUser.keycloak_user_id && !isKeycloakAdminConfigured()) {
        return res.status(503).json({
            error: 'Keycloak admin provisioning is not configured for user sync',
        });
    }

    const result = await query(
        `UPDATE users SET is_active = false WHERE id = $1 RETURNING id`,
        [idParsed.data]
    );

    await disableKeycloakUser(existingUser.keycloak_user_id);

    return res.json({ message: 'User deactivated' });
}
